//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSeguradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apolices
    {
        public int ApoliceId { get; set; }
        public int ClienteId { get; set; }
        public int Marca { get; set; }
        public int Modelo { get; set; }
        public int AnoFabricacao { get; set; }
        public int AnoModelo { get; set; }
        public int Combustivel { get; set; }
        public string Chassi { get; set; }
        public string Placa { get; set; }
        public bool Roubo { get; set; }
        public bool Vidros { get; set; }
        public bool Acidentes { get; set; }
        public bool DanosTerceiros { get; set; }
        public bool FranquiaRed { get; set; }
        public decimal ValorDoBem { get; set; }
        public decimal ValorFranquia { get; set; }
        public decimal ValorApolice { get; set; }
        public decimal ValorPremio { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Marcas Marcas { get; set; }
        public virtual Modelos Modelos { get; set; }
    }
}
