//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSeguradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelaFIPE
    {
        public int MarcaID { get; set; }
        public int ModeloID { get; set; }
        public int Ano { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Marcas Marcas { get; set; }
        public virtual Modelos Modelos { get; set; }
    }
}
